-- STORE Table
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE store CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
 
-- SELLER Table
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE seller CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
 
-- RETURN Table
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE return CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
 
-- PRODUCT Table
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE product CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
 
-- ORDER_PRODUCT Table
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE order_product CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
 
-- CUSTOMER_ORDER Table
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CUSTOMER_ORDER CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
 
-- FEEDBACK Table
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE feedback CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
 
-- DISCOUNT Table
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE discount CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
 
-- CUSTOMER Table
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE customer CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/
 
-- CATEGORY Table
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE category CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN

            RAISE;
        END IF;
END;
/

DROP VIEW RETURNED_PRODUCTS_DETAILS;
DROP VIEW Customer_Reliability_Index;
DROP VIEW Order_Delivery_Date;
DROP VIEW NUMBER_OF_RETURNABLE_DAYS;
DROP VIEW category_view;
DROP VIEW store_for_feedback;
DROP VIEW store_average_rating_view;
DROP VIEW product_discount_association;
DROP VIEW order_product_actual_price_per_unit;
DROP VIEW order_total_price_per_unit;
DROP VIEW refund_amount_view;
DROP VIEW accepted_returns_view;
DROP VIEW CHECK_APPROVED_RETURNS_BY_SYSTEM;

DROP SEQUENCE CUSTOMER_ID_SEQ;
DROP SEQUENCE CATEGORY_ID_SEQ;
DROP SEQUENCE DISCOUNT_ID_SEQ;
DROP SEQUENCE SELLER_ID_SEQ;
DROP SEQUENCE PRODUCT_ID_SEQ;
DROP SEQUENCE ORDER_ID_SEQ;
DROP SEQUENCE ORDER_PRODUCT_ID_SEQ;
DROP SEQUENCE STORE_ID_SEQ;
DROP SEQUENCE RETURN_ID_SEQ;
DROP SEQUENCE FEEDBACK_ID_SEQ;